import { pendingSelected } from './pending-selection.js';
import { esc, money, date } from '../../../utils/presentation.js';
import { itemEditor, validCompositionItem } from './composition-editing.js';
import { itemLabel } from './item-form.js';
const pencil='<svg viewBox="0 0 24 24" class="stroke-icon" aria-hidden="true"><path d="m15 4 5 5M4 20l4-1L20 7l-3-3L5 16z"/></svg>';
const remove='<svg viewBox="0 0 24 24" class="stroke-icon" aria-hidden="true"><path d="m6 6 12 12M6 18 18 6"/></svg>';
const pdf='<svg viewBox="0 0 28 28" aria-hidden="true"><path d="M7 2h10l6 6v17H7zM17 2v7h6" fill="none" stroke="currentColor" stroke-width="1.5"/><rect x="1" y="12" width="23" height="10" rx="2" fill="currentColor"/><text x="12.5" y="19.5" text-anchor="middle" font-family="Arial,sans-serif" font-size="8" font-weight="700" fill="var(--surface)">PDF</text></svg>';
export function compositionView({updating,allowDifference,canEdit,review,tab,work,pending,selected,transfer,draft,total,difference,visible,pages,stale,search,selection}) {
  const linked=draft.itens;
  return `<div class="rastreio-shell" data-composition-view="${tab}" data-current-entry="${selected?.id||''}">
  <section class="panel-card"><header class="panel-head"><div><h2>${review?'Transferências com rastreio':tab==='conciliacao'?'Créditos pendentes':'Débitos pendentes'}</h2><p>${review?'Selecione um crédito ou débito para revisar a composição.':'Selecione uma movimentação para compor o rastreio.'}</p></div>${review?`<input id="trackingTitleSearch" class="search-box" type="search" aria-label="Buscar título nas transferências" placeholder="Número do título nas transferências" value="${esc(work.transferQuery||'')}">`:'<button class="table-tool" data-table-control="filter" aria-label="Filtrar pendências"><span>Filtrar</span></button>'}</header>
  <div class="transfer-list">${pending.map(entry=>`<button class="transfer-row ${selected?.id===entry.id?'active':''}" data-transfer="${entry.id}" aria-pressed="${selected?.id===entry.id}"><span class="transfer-date">${date(entry.data)}</span><span class="transfer-copy"><strong>${esc(entry.historico)}</strong><span>${entry.valor>0?'Crédito':'Débito'} · ${esc(entry.entidade||'Sem entidade')} · ${entry.codigo||`Extrato #${entry.id}`}${work.drafts[entry.id]?.dirty?' · Em edição':''}</span></span><span class="transfer-value ${entry.valor>0?'credit':'debit'}">${money(Math.abs(entry.valor))}</span></button>`).join('')||'<div class="table-empty"><strong>Nenhuma movimentação nesta visualização</strong><p>Revise os filtros ou selecione outra aba.</p></div>'}</div></section>
  <section class="panel-card composition-panel"><header class="panel-head"><div><h2>Composição por títulos</h2><p>${selected?`${esc(selected.historico)} · ${date(selected.data)}`:'Selecione uma movimentação na lista.'}</p></div><div class="composition-actions">${selected?`<span class="soft-badge">${esc(transfer?.codigo||`Extrato #${selected.id}`)}</span>`:''}${transfer&&!transfer.extrato_id?`<button type="button" class="text-link" data-associate-movement ${draft.dirty?'disabled':''}>Associar movimentação</button>`:''}<button type="button" class="row-icon-action composition-pdf" data-composition-pdf title="Baixar PDF da composição salva" aria-label="Baixar PDF da composição salva" ${!transfer||draft.dirty?'disabled':''}>${pdf}</button></div></header>
  <div class="link-summary"><div class="link-metric"><span>Transferência</span><strong>${money(selected?Math.abs(selected.valor):0)}</strong></div><div class="link-metric"><span>${transfer?.alocacoes_vazias?'Composição conhecida':'Composição'} · ${linked.length} itens</span><strong data-composition-total>${money(total)}</strong></div><div class="link-metric link-difference"><span>Diferença</span><strong data-composition-difference class="${difference===0&&selected?'ok':'warn'}">${money(difference)}</strong></div><button class="form-action primary" data-confirm-transfer ${!selected||(canEdit&&(stale||!linked.every(validCompositionItem)||(updating?!draft.dirty:!linked.length)||(!allowDifference&&difference!==0&&!(updating&&!linked.length))))?'disabled':''}>${review&&!canEdit?'Editar':updating?'Salvar alterações':'Rastrear transferência'}</button></div>
  ${stale?'<p class="composition-notice" role="alert">A transferência foi alterada. Descarte as alterações locais para carregar a composição atual.</p>':''}
  <div class="title-tabs"><button class="title-tab ${work.titleTab==='vinculados'?'active':''}" data-title-tab="vinculados">Vinculados <span class="soft-badge">${linked.length}</span></button><button class="title-tab ${work.titleTab==='todos'?'active':''}" data-title-tab="todos">Todos os títulos</button><button class="title-tab ${work.titleTab==='pendencias'?'active':''}" data-title-tab="pendencias">Todas as pendências</button><span class="composition-hint">${work.titleTab==='todos'?'Busca na base Qprof':work.titleTab==='pendencias'?'Recebimentos que aguardam saída':'Registros da composição'}</span></div>
  <div class="title-selection-summary" aria-live="polite"><span>Selecionados: <strong data-selected-count>${linked.length}</strong></span><span>Total selecionado: <strong data-selected-total>${money(total)}</strong></span>${transfer?`<span>Composição salva: <strong>${money(transfer.total_composicao)}</strong></span>`:''}</div>
  <div class="title-toolbar"><div class="title-search-group"><input id="titleSearch" class="search-box" type="search" aria-label="Pesquisar títulos" placeholder="Buscar título, cedente, sacado ou valor" value="${esc(work.query)}"><button class="table-tool" data-table-control="filter" aria-label="Filtrar tabela"><span>Filtrar</span></button></div><div class="composition-edit-actions"><button type="button" class="table-tool" data-items-edit ${canEdit&&selected&&work.titleTab==='vinculados'&&(linked.length||work.editing)?'':'disabled'}>${work.editing?remove:pencil}<span>${work.editing?'Cancelar':'Editar'}</span></button><button type="button" class="table-tool" data-items-save ${canEdit&&work.editing&&work.titleTab==='vinculados'?'':'disabled'}><svg viewBox="0 0 24 24" class="stroke-icon" aria-hidden="true"><path d="M5 3h12l4 4v14H3V3h2Zm2 0v7h9V3M7 21v-8h10v8"/></svg><span>Salvar</span></button><button type="button" class="table-tool" data-item-new ${canEdit&&selected&&work.titleTab==='vinculados'?'':'disabled'}><span>＋ Criar registro</span></button></div></div>
  <div class="title-table-wrap" aria-busy="${!!search?.loading}" aria-live="polite"><table class="title-table"><thead><tr><th aria-label="Ações"><button type="button" class="check ${selection.checked?'on':''} ${selection.mixed?'mixed':''}" role="checkbox" aria-checked="${selection.mixed?'mixed':selection.checked}" data-titles-select-all aria-label="${esc(selection.label)}" title="${esc(selection.title)}" ${!canEdit||!selected||selection.disabled?'disabled':''}></button></th><th>Tipo</th><th>Título</th><th>Cedente</th><th>Sacado</th><th class="money">Valor (R$)</th></tr></thead><tbody>${visible.map(row=>{
    const source=row._source,pending=row._pending,item=pending?pendingSelected(draft,row):source?linked.find(item=>item.qprof_titulo_id===source):row;
    return `<tr class="${item?'selected':''}"><td><div class="composition-row-actions">${pending?`<button class="check ${item?'on':''}" data-pending-title="${pending}" aria-label="${item?'Desvincular':'Selecionar'} pendência ${esc(row.titulo)}" aria-pressed="${!!item}" ${canEdit&&selected?'':'disabled'}></button>`:source?`<button class="check ${item?'on':''}" data-title="${source}" aria-label="${item?'Desvincular':'Vincular'} título ${esc(row.titulo)}" aria-pressed="${!!item}" ${canEdit&&selected?'':'disabled'}></button>`:`<button class="row-icon-action" data-item-remove="${row._key}" ${canEdit?'':'disabled'} aria-label="Desvincular item ${esc(row.titulo||itemLabel(row.tipo))}">${remove}</button>`}${item&&work.titleTab==='vinculados'&&!work.editing?`<button class="row-icon-action" data-item-edit="${item._key}" ${canEdit?'':'disabled'} aria-label="Editar item ${esc(item.titulo||itemLabel(item.tipo))}">${pencil}</button>`:''}</div></td>${canEdit&&work.editing&&work.titleTab==='vinculados'?['tipo','titulo','cedente','sacado','valor_reais'].map(key=>`<td class="inline-edit-cell">${itemEditor(row,key)}</td>`).join(''):`<td>${itemLabel(row.tipo)}${row.efeito==='compensacao'?'<span class="cell-sub">Compensação de saldo<br>Não soma ao total bancário</span>':''}</td><td>${row.registro_id?`<button type="button" class="text-link" data-control-record="${row.registro_id}" aria-label="Ver percurso ${esc(row.titulo||itemLabel(row.tipo))}">${esc(row.titulo||'Ver percurso')}</button>`:esc(row.titulo||'—')}</td><td title="${esc(row.cedente||'')}">${esc(row.cedente||'—')}</td><td>${esc(row.sacado||'—')}</td><td class="money">${row.valor===null?'Não informado':money(row.valor)}</td>`}</tr>`;
  }).join('')||`<tr><td colspan="6"><div class="table-empty">${esc(search?.message||'Nenhum registro nesta visualização. Revise os filtros ou crie um registro.')}${search?.error?'<button class="table-tool" data-title-retry>Tentar novamente</button>':''}</div></td></tr>`}</tbody></table></div>
  <footer class="composition-footer"><span data-composition-status>${draft.dirty?'Alterações ainda não salvas.':'A composição não cria movimentações no Extrato.'}</span><div class="composition-footer-actions"><div class="table-pagination"><button class="page-nav" data-title-prev aria-label="Página anterior de títulos" ${work.page===1||search?.loading?'disabled':''}>‹</button><span>${work.page} / ${pages}</span><button class="page-nav" data-title-next aria-label="Próxima página de títulos" ${work.page>=pages||search?.loading?'disabled':''}>›</button></div><button type="button" class="table-tool" data-composition-cancel ${draft.dirty||(review&&canEdit)?'':'hidden'}>${review?'Cancelar edição':'Descartar alterações'}</button></div></footer></section></div>`;
}
